parameters:

    adapter: Postgres    
    event_dispatcher.class: Symfony\Component\EventDispatcher\EventDispatcher
    event_listener.class: Rentgen\Listener
    connection_config.class: Rentgen\Database\ConnectionConfig

    command.factory.class: Rentgen\Schema\Factory
    command.manipulation.create_table.class: Rentgen\Schema\@@adapter@@\Manipulation\CreateTableCommand
    command.manipulation.drop_table.class: Rentgen\Schema\@@adapter@@\Manipulation\DropTableCommand
    command.manipulation.add_foreign_key.class: Rentgen\Schema\@@adapter@@\Manipulation\AddForeignKeyCommand
    command.manipulation.drop_constraint.class: Rentgen\Schema\@@adapter@@\Manipulation\DropConstraintCommand

services:

    event_dispatcher:
        class: "%event_dispatcher.class%"

    event_listener:
        class: "%event_listener.class%"

    connection_config:
        class: "%connection_config.class%"

    connection:
        class: Rentgen\Database\Connection
        arguments: [@connection_config]

    AbstractCommand:
        class: Rentgen\Schema\Command
        abstract: true
        calls:
            - [setEventDispatcher, [ @event_dispatcher ]]
            - [setConnection, [ @connection ]]

    command_factory:
        class: "%command.factory.class%"
        calls:
             - [setAdapter, ["%adapter%"]]

    create_table:
        parent: AbstractCommand
        factory_service: command_factory
        factory_method: setClass
        arguments: [%command.manipulation.create_table.class%]

    drop_table:
        parent: AbstractCommand
        factory_service: command_factory
        factory_method: setClass
        arguments: [%command.manipulation.drop_table.class%]

    add_foreign_key:
        parent: AbstractCommand
        factory_service: command_factory
        factory_method: setClass
        arguments: [%command.manipulation.add_foreign_key.class%]

    drop_constraint:
        parent: AbstractCommand
        factory_service: command_factory
        factory_method: setClass
        arguments: [%command.manipulation.drop_constraint.class%]

    event_table:
        class: Rentgen\Event\TableEvent
        tags:
            - { name: table, event: table.create, method: onCreateTable }
            - { name: table, event: table.drop,   method: onDropTable }
