parameters:

    adapter: Postgres
    factory.class: Rentgen\Factory
    event_dispatcher.class: Symfony\Component\EventDispatcher\EventDispatcher
    event_listener.class: Rentgen\Listener
    connection_config.class: Rentgen\Database\ConnectionConfig

services:
    factory:
        class: "%factory.class%"

        calls:
             - [setAdapter, ["%adapter%"]]
    event_dispatcher:
        class: "%event_dispatcher.class%"

    event_listener:
        class: "%event_listener.class%"

    connection_config:
        class: "%connection_config.class%"

    connection:
        class: Rentgen\Database\Connection
        arguments: [@connection_config]


    AbstractCommand:
        class: Rentgen\Schema\Command
        abstract: true
        calls:
            - [setEventDispatcher, [ @event_dispatcher ]]
            - [setConnection, [ @connection ]]

    create_table:
        parent: AbstractCommand
        factory_service: Factory
        factory_method: setCommand
        arguments: ["CreateTableCommand"]

    drop_table:
        parent: AbstractCommand
        factory_service: Factory
        factory_method: setCommand
        arguments: ["DropTableCommand"]

    event_table:
        class: Rentgen\Event\TableEvent
        tags:
            - { name: table, event: table.create, method: onCreateTable }
            - { name: table, event: table.drop,   method: onDropTable }
